# Generated by Django 4.0 on 2021-12-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='gender',
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.BooleanField(choices=[('Regular', False), ('Admin', True)], default=False),
        ),
    ]
