# Generated by Django 4.0 on 2021-12-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0002_remove_teammember_gender_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.BooleanField(choices=[(False, 'Regular'), (True, 'Admin')], default=False),
        ),
    ]
